-- ------------------------------------------------------------------------------
-- DROP TABLES
-- ------------------------------------------------------------------------------
DROP TABLE ANSWER;
DROP TABLE HISTORY;
DROP TABLE QUESTION;
DROP TABLE USERS;
DROP TABLE SUBJECT;


-- ------------------------------------------------------------------------------
-- CREATE TABLES
-- ------------------------------------------------------------------------------
CREATE TABLE USERS (
	USER_ID					INT NOT NULL PRIMARY KEY AUTO_INCREMENT		COMMENT 'ユーザID',
	ACCOUNT_ID				VARCHAR(64) NOT NULL						COMMENT 'アカウントID',
	PASSWORD				VARCHAR(128) NOT NULL						COMMENT 'パスワード',
	LAST_NAME				VARCHAR(32) NOT NULL						COMMENT '姓',
	FIRST_NAME				VARCHAR(32) NOT NULL						COMMENT '名',
	LAST_NAME_KANA			VARCHAR(32) NOT NULL						COMMENT '姓カナ',
	FIRST_NAME_KANA			VARCHAR(32) NOT NULL						COMMENT '名カナ',
	USER_TYPE				CHAR(1) NOT NULL							COMMENT 'ユーザタイプ（管理者:1、学習者:0）',
	BIRTH_DATE				DATE NOT NULL								COMMENT '生年月日',
	NOTICE_MAIL				VARCHAR(1024)								COMMENT '通知先メール（区切り文字は「|@|」）'
)
COMMENT 'ユーザ情報';
ALTER TABLE USERS
	ADD CONSTRAINT USERS_UK_0 UNIQUE KEY (ACCOUNT_ID);

CREATE TABLE SUBJECT
(
	SUBJECT_ID				INT NOT NULL PRIMARY KEY AUTO_INCREMENT		COMMENT '科目ID',
	TARGET_AGE				SMALLINT									COMMENT '対象年齢',
	SUBJECT_TYPE			SMALLINT									COMMENT '科目種別（0:通常）',
	DESCRIPTION				VARCHAR(128)								COMMENT '科目名'
)
COMMENT '科目情報';

CREATE TABLE QUESTION
(
	QUESTION_ID				INT NOT NULL PRIMARY KEY AUTO_INCREMENT		COMMENT '問題ID',
	SUBJECT_ID				INT NOT NULL								COMMENT '科目ID',
	QUESTION				VARCHAR(1024) NOT NULL						COMMENT '問題',
	CORRECT					VARCHAR(256) NOT NULL						COMMENT '解答',
	SEP_CHAR				VARCHAR(4)									COMMENT '複数解答の区切り文字',
	REMARK					VARCHAR(1024)								COMMENT '説明'
)
COMMENT '問題情報';
ALTER TABLE QUESTION
	ADD CONSTRAINT QUESTION_FK_0 FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT (SUBJECT_ID);

CREATE TABLE HISTORY
(
	HISTORY_ID				INT NOT NULL PRIMARY KEY AUTO_INCREMENT		COMMENT '履歴ID',
	REGIST_DATE				DATE NOT NULL								COMMENT '登録日時',
	USER_ID					INT NOT NULL								COMMENT 'ユーザID',
	ELAPSED					INT											COMMENT '経過時間',
	CORRECT_PERCENT			DECIMAL(5,2)								COMMENT '正答率'
)
COMMENT '履歴情報';
ALTER TABLE HISTORY
	ADD CONSTRAINT HISTORY_FK_0 FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);

CREATE TABLE ANSWER
(
	ANSWER_ID				INT NOT NULL PRIMARY KEY AUTO_INCREMENT		COMMENT '回答ID',
	HISTORY_ID				INT NOT NULL								COMMENT '履歴ID',
	QUESTION_ID				INT NOT NULL								COMMENT '問題ID',
	ANSWER					VARCHAR(256)								COMMENT '回答',
	CORRECT_WRONG			CHAR(1)										COMMENT '正誤（正:1, 誤:0）'
)
COMMENT '回答情報';
ALTER TABLE ANSWER
	ADD CONSTRAINT ANSWER_FK_0 FOREIGN KEY (HISTORY_ID) REFERENCES HISTORY (HISTORY_ID),
	ADD CONSTRAINT ANSWER_FK_1 FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION (QUESTION_ID);

